package com.relengxing.bean;

import java.util.Date;

public class Date1c20 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date1c20.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date1c20.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date1c20.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date1c20.temerature
     *
     * @mbg.generated
     */
    private Integer temerature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date1c20.humidity
     *
     * @mbg.generated
     */
    private Integer humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date1c20.electricity
     *
     * @mbg.generated
     */
    private Integer electricity;


    @Override
    public String toString() {
        return "Date1c20{" +
                "id=" + id +
                ", address='" + address + '\'' +
                ", time=" + time +
                ", temerature=" + temerature +
                ", humidity=" + humidity +
                ", electricity=" + electricity +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date1c20.id
     *
     * @return the value of date1c20.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date1c20.id
     *
     * @param id the value for date1c20.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date1c20.address
     *
     * @return the value of date1c20.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date1c20.address
     *
     * @param address the value for date1c20.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date1c20.time
     *
     * @return the value of date1c20.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date1c20.time
     *
     * @param time the value for date1c20.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date1c20.temerature
     *
     * @return the value of date1c20.temerature
     *
     * @mbg.generated
     */
    public Integer getTemerature() {
        return temerature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date1c20.temerature
     *
     * @param temerature the value for date1c20.temerature
     *
     * @mbg.generated
     */
    public void setTemerature(Integer temerature) {
        this.temerature = temerature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date1c20.humidity
     *
     * @return the value of date1c20.humidity
     *
     * @mbg.generated
     */
    public Integer getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date1c20.humidity
     *
     * @param humidity the value for date1c20.humidity
     *
     * @mbg.generated
     */
    public void setHumidity(Integer humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date1c20.electricity
     *
     * @return the value of date1c20.electricity
     *
     * @mbg.generated
     */
    public Integer getElectricity() {
        return electricity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date1c20.electricity
     *
     * @param electricity the value for date1c20.electricity
     *
     * @mbg.generated
     */
    public void setElectricity(Integer electricity) {
        this.electricity = electricity;
    }
}