package com.relengxing.mapper;

import com.relengxing.bean.Date1c20;

import java.util.List;

public interface Date1c20Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date1c20
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date1c20
     *
     * @mbg.generated
     */
    int insert(Date1c20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date1c20
     *
     * @mbg.generated
     */
    int insertSelective(Date1c20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date1c20
     *
     * @mbg.generated
     */
    Date1c20 selectByPrimaryKey(Integer id);

    List<Date1c20> selectAllDate1c20();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date1c20
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Date1c20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date1c20
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Date1c20 record);
}